In [2]:
import torch
import torch.nn as nn


In [3]:
# create a model class
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
        


In [4]:
# create a dataset to test
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4388],
        [0.4207],
        [0.4663],
        [0.4828],
        [0.4556],
        [0.4467],
        [0.4762],
        [0.4654],
        [0.4950],
        [0.4992]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear.weight

Parameter containing:
tensor([[ 0.1899, -0.2889,  0.1177, -0.2180, -0.1970]], requires_grad=True)

In [6]:
model.linear.bias

Parameter containing:
tensor([0.0223], requires_grad=True)

In [7]:
from torchinfo import summary
summary(model,(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [8]:
class my_model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        
        return out
    
        

In [9]:
# create a dataset to test
features = torch.rand(10,5)

# create model
model = my_model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6074],
        [0.5870],
        [0.6013],
        [0.6019],
        [0.6102],
        [0.6012],
        [0.6155],
        [0.5923],
        [0.5877],
        [0.5974]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear1.weight

Parameter containing:
tensor([[-0.2854, -0.0042,  0.2292, -0.2090, -0.0252],
        [-0.1870, -0.3710, -0.2532, -0.1203,  0.0564],
        [-0.1991, -0.3597, -0.4379, -0.2041,  0.3522]], requires_grad=True)

In [11]:
model.linear2.weight

Parameter containing:
tensor([[-0.2882,  0.3284,  0.3826]], requires_grad=True)

In [13]:
summary(model,(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
my_model                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [14]:
# using sequential 

class my_model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid(),
            
        )
        
    def forward(self,features):
        out = self.network(features)
        return out

In [15]:
# create a dataset to test
features = torch.rand(10,5)

# create model
model = my_model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.6388],
        [0.6622],
        [0.6698],
        [0.6800],
        [0.6721],
        [0.6672],
        [0.6359],
        [0.6655],
        [0.6512],
        [0.6722]], grad_fn=<SigmoidBackward0>)