In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('data/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,

In [11]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [12]:
X_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

## Defining the model

In [20]:
class my_model():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    def forward(self,X):
        z = torch.matmul(X,self.weights)+self.bias
        return torch.sigmoid(z)
    
    def loss_function(self,y_pred, y):
        # clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
        loss =  -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss
        

In [21]:
learning_rate = 0.1
epochs = 25

## Training Pipeline 


### **1. Model Initialization**
```python
model = my_model(X_train_tensor)
```
- creating an instance of your model class, `my_model`. 
- Inside the `__init__` method, you initialize the model’s **parameters**:
  - `weights`: Random initial values with `requires_grad=True`.
  - `bias`: Zero-initialized with `requires_grad=True`.
- These parameters are trainable and will be updated during training.

---

### **2. Training Loop**
The loop iterates over a predefined number of `epochs`. Each epoch represents one full pass over the training data.

---

#### **Step 2.1: Forward Pass**
```python
y_pred = model.forward(X_train_tensor)
```
- The input data `X_train_tensor` is passed to the model’s `forward` method.
- Inside the forward method:
  - compute the linear combination: `z = X @ weights + bias` (matrix multiplication and bias addition).
  - Apply the **sigmoid activation** function: `torch.sigmoid(z)`, which gives predictions (`y_pred`) in the range `[0, 1]`.

---

#### **Step 2.2: Loss Calculation**
```python
loss = model.loss_function(y_pred, y_train_tensor)
```
- calculate the **binary cross-entropy loss**:
  - This measures the error between the predicted probabilities (`y_pred`) and the actual labels (`y_train_tensor`).
  - If the predictions are far from the true labels, the loss will be higher.
  - The loss is a scalar value that quantifies how well the model is performing.

---

#### **Step 2.3: Backward Pass**
```python
loss.backward()
```
- This is where **autograd** (PyTorch’s automatic differentiation engine) comes into play.
- The `loss.backward()` call:
  - Computes the **gradients of the loss** with respect to the model’s parameters (`weights` and `bias`).
  - These gradients are stored in `model.weights.grad` and `model.bias.grad`.
  - The gradients represent how much each parameter contributes to the loss, and they are used to update the parameters in the next step.

---

#### **Step 2.4: Parameter Updates**
```python
with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad
```
- The parameters (`weights` and `bias`) are updated using **gradient descent**:
  - Subtract the product of the gradient (`.grad`) and the learning rate (`learning_rate`).
- **Why `torch.no_grad()`?**
  - This ensures that the update operation (the subtraction) is not tracked in the computation graph, as these updates are not part of the backpropagation process. 
  - It saves memory and computation time.

---

#### **Step 2.5: Clear Gradients**
```python
model.weights.grad.zero_()
model.bias.grad.zero_()
```
- After updating the parameters, the gradients (`.grad`) are **cleared**.
- **Why?**
  - Gradients accumulate in PyTorch by default. If you don’t clear them, gradients from the previous epoch will be added to the new gradients in the next epoch, which will result in incorrect updates.
  - Clearing gradients ensures that only the gradients for the current epoch are used.

---

### **3. Output**
```python
print(f'Epoch {epoch+1}, Loss: {loss.item()}')
```
- At the end of each epoch, print the loss value.
- This allows you to monitor how the model is improving (or not) over time.

---

### **Summary of the Flow**
1. **Forward Pass**:
   - Use input data to calculate predictions (`y_pred`).
   - Compute the loss based on how far predictions are from true labels.

2. **Backward Pass**:
   - Calculate the gradients of the loss with respect to the model’s parameters.

3. **Parameter Update**:
   - Adjust the parameters (`weights` and `bias`) using gradient descent to minimize the loss.

4. **Clear Gradients**:
   - Reset gradients for the next epoch to avoid accumulation.

This loop continues for the specified number of epochs, gradually improving the model’s predictions by iteratively minimizing the loss.

In [25]:
# create model
model = my_model(X_train_tensor)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate 
    loss = model.loss_function(y_pred, y_train_tensor)
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')
    
    # backward pass
    loss.backward()
    
    # parameters update 
    with torch.no_grad():
        model.weights -= learning_rate*model.weights.grad
        model.bias -= learning_rate*model.bias.grad
        
    # clear the gradients 
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    # print loss in each epoch
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')


Epoch 1, Loss: 3.68338144627563
Epoch 1, Loss: 3.68338144627563
Epoch 2, Loss: 3.5685166044414016
Epoch 2, Loss: 3.5685166044414016
Epoch 3, Loss: 3.4495094311852856
Epoch 3, Loss: 3.4495094311852856
Epoch 4, Loss: 3.325429064013062
Epoch 4, Loss: 3.325429064013062
Epoch 5, Loss: 3.1974806079893234
Epoch 5, Loss: 3.1974806079893234
Epoch 6, Loss: 3.0679085268573427
Epoch 6, Loss: 3.0679085268573427
Epoch 7, Loss: 2.931534326732786
Epoch 7, Loss: 2.931534326732786
Epoch 8, Loss: 2.793201242988843
Epoch 8, Loss: 2.793201242988843
Epoch 9, Loss: 2.6506859274926184
Epoch 9, Loss: 2.6506859274926184
Epoch 10, Loss: 2.5047622634478186
Epoch 10, Loss: 2.5047622634478186
Epoch 11, Loss: 2.3576303670538583
Epoch 11, Loss: 2.3576303670538583
Epoch 12, Loss: 2.2121848022615263
Epoch 12, Loss: 2.2121848022615263
Epoch 13, Loss: 2.070938682295269
Epoch 13, Loss: 2.070938682295269
Epoch 14, Loss: 1.926985120657926
Epoch 14, Loss: 1.926985120657926
Epoch 15, Loss: 1.7885279694299985
Epoch 15, Loss: 1

In [27]:
model.weights

tensor([[ 0.2627],
        [ 0.4002],
        [-0.3983],
        [ 0.0522],
        [-0.0531],
        [ 0.3742],
        [ 0.3264],
        [ 0.2683],
        [-0.0468],
        [ 0.0743],
        [ 0.1659],
        [ 0.5742],
        [ 0.0941],
        [-0.1674],
        [ 0.1826],
        [-0.0565],
        [-0.1015],
        [ 0.0394],
        [ 0.2886],
        [-0.0169],
        [ 0.1638],
        [ 0.4434],
        [ 0.2574],
        [-0.4077],
        [ 0.1933],
        [-0.4443],
        [-0.3691],
        [-0.2640],
        [ 0.1698],
        [-0.0158]], dtype=torch.float64, requires_grad=True)

In [28]:
model.bias

tensor([-0.1450], dtype=torch.float64, requires_grad=True)

### Evaluation 

In [35]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy}')
    

Accuracy: 0.6055709719657898


In [32]:
print(y_pred)

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
      