In [3]:
import torch

# Creating Tensors

### Using empty

This function just allocates the memory for the tensor size you pass as the argument


In [2]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Using zeeros 

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Using Ones

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Using rand

In [10]:
torch.rand(2,3)

tensor([[0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000]])

In [9]:
torch.manual_seed(0)
torch.randn(2,3)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])

### Using tensor

In [11]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

### Other ways

In [12]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [15]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

### Identity matrix

In [18]:
torch.eye(5)  # diagonals items are 1 rest items are 0 and the argument tells the size of the tensor in this case 5*5

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.full((2,3),5) # first argument is the size of the tensor and the second is the element 

tensor([[5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [23]:
x = torch.tensor([[1,2,4],[3,4,5]])
x

tensor([[1, 2, 4],
        [3, 4, 5]])

In [22]:
x.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Data Types

In [27]:
x.dtype

torch.int64

In [31]:
# assign dtype
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [32]:
# we can change the datatype of a tensor using .to function
x.to(torch.float32)

tensor([[1., 2., 4.],
        [3., 4., 5.]])

In [34]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742]])

# Mathematical Operations

## 1. Scaler Operations

In [35]:
x = torch.randn(2,2)

In [36]:
x

tensor([[-0.8567,  1.1006],
        [-1.0712,  0.1227]])

In [37]:
x+2

tensor([[1.1433, 3.1006],
        [0.9288, 2.1227]])

In [38]:
x-3

tensor([[-3.8567, -1.8994],
        [-4.0712, -2.8773]])

In [39]:
x*3

tensor([[-2.5700,  3.3018],
        [-3.2136,  0.3681]])

In [40]:
x/3

tensor([[-0.2856,  0.3669],
        [-0.3571,  0.0409]])

## 2. Element wise Operation

In [42]:
a = torch.randn(2,3)
b = torch.randn(2,3)
print(a)
print(b)


tensor([[-0.5663,  0.3731, -0.8920],
        [-1.5091,  0.3704,  1.4565]])
tensor([[ 0.9398,  0.7748,  0.1919],
        [ 1.2638, -1.2904, -0.7911]])


In [43]:
# add 
a+b


tensor([[ 0.3735,  1.1480, -0.7001],
        [-0.2453, -0.9200,  0.6654]])

In [44]:
a-b

tensor([[-1.5061, -0.4017, -1.0839],
        [-2.7729,  1.6608,  2.2476]])

In [45]:
a*b

tensor([[-0.5322,  0.2891, -0.1711],
        [-1.9072, -0.4780, -1.1522]])

In [46]:
c = torch.tensor([1,-2,-3,4,5])

In [47]:
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [48]:
torch.neg(c)

tensor([-1,  2,  3, -4, -5])

In [49]:
torch.round(a)

tensor([[-1.,  0., -1.],
        [-2.,  0.,  1.]])

In [50]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [51]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [52]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [53]:
# clamp
torch.clamp(d,min=2,max =3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

You reduce the entire tensor in to a single number

In [63]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [71]:
e

tensor([[3., 4., 5.],
        [0., 8., 2.]])

In [57]:
# sum
torch.sum(e)

tensor(37)

In [60]:
# sum along columns
torch.sum(e,0)

tensor([10, 15, 12])

In [61]:
# sum along rows
torch.sum(e,1)

tensor([15, 22])

In [64]:
# mean
torch.mean(e)

tensor(3.6667)

In [65]:
# mean along col
torch.mean(e,0)

tensor([1.5000, 6.0000, 3.5000])

In [66]:
# median
torch.median(e)

tensor(3.)

In [67]:
torch.max(e)

tensor(8.)

In [68]:
torch.min(e)

tensor(0.)

In [69]:
torch.prod(e)


tensor(0.)

In [70]:
e

tensor([[3., 4., 5.],
        [0., 8., 2.]])

In [72]:
# Standard deviation 
torch.std(e)

tensor(2.7325)

In [73]:
# Variance 
torch.var(e)

tensor(7.4667)

In [75]:
# argmax    returns the index of the max element
torch.argmax(e)

tensor(4)

In [76]:
torch.argmin(e)

tensor(3)

## 4. Matrix Operations

In [81]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(g)
print(f)

tensor([[7, 2],
        [5, 6],
        [6, 5]])
tensor([[2, 8, 5],
        [6, 6, 5]])


In [82]:
# matrix mult
torch.matmul(f,g)

tensor([[ 84,  77],
        [102,  73]])

In [83]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([4,5])

torch.dot(vector1,vector2)

tensor(14)

In [84]:
# transpose 
f

tensor([[2, 8, 5],
        [6, 6, 5]])

In [88]:
torch.transpose(f,0,1)

tensor([[2, 6],
        [8, 6],
        [5, 5]])

In [89]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[4., 0., 8.],
        [1., 7., 8.],
        [5., 4., 4.]])

In [90]:
torch.det(h)

tensor(-264.)

### Comparison operations


In [91]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)


In [92]:
# greater than 
i>j

tensor([[ True, False,  True],
        [ True, False,  True]])

In [93]:
# less than 
i<j

tensor([[False,  True, False],
        [False,  True, False]])

In [94]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [95]:
# log

torch.log(i)

tensor([[2.0794, 1.3863, 1.3863],
        [2.1972,   -inf, 1.9459]])

In [96]:
torch.exp(i)

tensor([[2.9810e+03, 5.4598e+01, 5.4598e+01],
        [8.1031e+03, 1.0000e+00, 1.0966e+03]])

In [97]:
torch.sqrt(i)

tensor([[2.8284, 2.0000, 2.0000],
        [3.0000, 0.0000, 2.6458]])

In [98]:
# sigmoid
torch.sigmoid(i)

tensor([[0.9997, 0.9820, 0.9820],
        [0.9999, 0.5000, 0.9991]])

In [100]:
# softmax
torch.softmax(x, dim=1)

tensor([[0.1238, 0.8762],
        [0.2326, 0.7674]])

In [101]:
torch.relu(i)

tensor([[8, 4, 4],
        [9, 0, 7]])

In [108]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)


tensor([[0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747]])
tensor([[0.4638, 0.0508, 0.2630],
        [0.8405, 0.4968, 0.2515]])


In [109]:
# it is an inplace operation it will store the result in m instead  of creating a new space in memory
m.add_(n)

tensor([[0.9207, 0.6520, 1.0809],
        [1.8141, 1.3143, 1.2262]])

In [110]:
m

tensor([[0.9207, 0.6520, 1.0809],
        [1.8141, 1.3143, 1.2262]])

In [111]:
n

tensor([[0.4638, 0.0508, 0.2630],
        [0.8405, 0.4968, 0.2515]])

In [112]:
torch.relu(m)

tensor([[0.9207, 0.6520, 1.0809],
        [1.8141, 1.3143, 1.2262]])

In [113]:
m.relu_()

tensor([[0.9207, 0.6520, 1.0809],
        [1.8141, 1.3143, 1.2262]])

In [114]:
m

tensor([[0.9207, 0.6520, 1.0809],
        [1.8141, 1.3143, 1.2262]])

for inplace operation just add '_' infront of the function 

## Copying Tensors

In [115]:
a = torch.randn(2,3)
a

tensor([[ 1.2827, -0.5575,  0.1922],
        [ 0.5196,  0.6670, -0.7107]])

In [116]:
b = a

In [117]:
b

tensor([[ 1.2827, -0.5575,  0.1922],
        [ 0.5196,  0.6670, -0.7107]])

In [118]:
id(a)

4646577616

In [119]:
id(b)

4646577616

In [120]:
a[0][0] = 0

In [121]:
a

tensor([[ 0.0000, -0.5575,  0.1922],
        [ 0.5196,  0.6670, -0.7107]])

In [122]:
b

tensor([[ 0.0000, -0.5575,  0.1922],
        [ 0.5196,  0.6670, -0.7107]])

when we just assign it using '=' we don't really copy it we just give the new variable same memory location so if we change something in a
it will reflect in b as well . so it is not true copying 

In [123]:
b = a.clone()

In [124]:
a

tensor([[ 0.0000, -0.5575,  0.1922],
        [ 0.5196,  0.6670, -0.7107]])

In [125]:
b

tensor([[ 0.0000, -0.5575,  0.1922],
        [ 0.5196,  0.6670, -0.7107]])

In [126]:
print(id(a))
print(id(b))

4646577616
4646576464


## Tensor Operation on GPU

When you create tensors in PyTorch on a GPU, they are stored in the GPU's VRAM (Video RAM), which is dedicated memory on the GPU card.

In [127]:
torch.backends.mps.is_available()

True

In [128]:
device = torch.device("mps")

In [129]:
# creating a new tensor on Gpu
torch.rand((2,3),device=device)

tensor([[0.3664, 0.0755, 0.7784],
        [0.1186, 0.7737, 0.1323]], device='mps:0')

In [131]:
# moving an existing tensor to GPU
x.to(device)

tensor([[-0.8567,  1.1006],
        [-1.0712,  0.1227]], device='mps:0')

In [138]:
import torch
import time

size = 10000

# Creating random tensors on CPU
mat_cpu1 = torch.randn(size, size)
mat_cpu2 = torch.randn(size, size)

# Measuring time for CPU
start = time.time()
result_cpu = torch.matmul(mat_cpu1, mat_cpu2)
end = time.time()
cpu_time = end - start
print(f"time on CPU: {cpu_time:.4f} seconds")

# Creating random tensors on GPU
device = 'mps'  
mat_gpu1 = mat_cpu1.to(device)
mat_gpu2 = mat_cpu2.to(device)

# Measuring time for GPU
start = time.time()
result_gpu = torch.matmul(mat_gpu1, mat_gpu2)
torch.mps.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start

print(f"time on GPU: {gpu_time:.4f} seconds")

# Comparing performance
print(f"Speedup (CPU/GPU): {cpu_time / gpu_time:.2f}")


time on CPU: 2.1993 seconds
time on GPU: 1.8269 seconds
Speedup (CPU/GPU): 1.20


## Reshaping Tensors

In [4]:
one = torch.ones(4,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
one.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [7]:
# flatten
one.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
k = torch.rand(2,3,4)
k

tensor([[[0.8854, 0.3333, 0.8100, 0.9400],
         [0.0056, 0.8236, 0.9639, 0.7762],
         [0.1253, 0.5489, 0.1559, 0.0682]],

        [[0.1291, 0.5766, 0.9145, 0.8038],
         [0.1342, 0.2373, 0.2181, 0.4657],
         [0.7543, 0.1830, 0.6762, 0.4912]]])

In [12]:
k.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [13]:
img = torch.rand(226,226,3)
img.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [14]:
l = torch.rand(1,20)
l

tensor([[0.9893, 0.4836, 0.0228, 0.8004, 0.7519, 0.5230, 0.5053, 0.5292, 0.8012,
         0.9227, 0.3090, 0.0734, 0.9980, 0.6559, 0.2470, 0.8570, 0.3705, 0.2029,
         0.9478, 0.1284]])

In [16]:
print(l.squeeze(0).shape)
print(l.squeeze(0))

torch.Size([20])
tensor([0.9893, 0.4836, 0.0228, 0.8004, 0.7519, 0.5230, 0.5053, 0.5292, 0.8012,
        0.9227, 0.3090, 0.0734, 0.9980, 0.6559, 0.2470, 0.8570, 0.3705, 0.2029,
        0.9478, 0.1284])


In [17]:
import numpy as np

In [18]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [19]:
b = a.numpy()
b

array([1, 2, 3])

In [20]:
type(b)

numpy.ndarray